sensors:
  - head_depth_camera

head_depth_camera:
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: /chapter11/head/depth_points
  max_range: 3.0
  point_subsample: 1
  # 按要求不对环境体素做预膨胀。
  padding_offset: 0.0
  padding_scale: 1.0
  max_update_rate: 1.0
  filtered_cloud_topic: /chapter11/head/filtered_cloud
